### ISSUE TITLE
Rules

### ISSUE THREAD

**Issue by makoto0610** [makoto0610/Mobster#10]
# **Task Details**
- [x] Come up with list of rules
- [x] Hard code list of rules on the Android
- [x] Make a drop down for rules
# **Acceptance Scenarios**
- Given: A user
- When: A user wants to view set of rules
- Then: User can navigate to the set of rules and view them
# **Done Done Criteria**
- [x] Ensure that there are no spelling/ grammar mistakes
- [x] Test that all the rules can be seen
- [x] Push code to the master branch on Git
