### ISSUE TITLE
Statistics Screen

### ISSUE THREAD

**Issue by anir1296** [makoto0610/Mobster#11]
# ****Task Details****
- [x] Create a page in the UI that displays user statistics
- [x] Program the backend to query database to retrieve user statistics, including number of questions answered and number of questions asked
# **Acceptance scenarios**
- Given: A registered user
- When: A user wants to check his statistics/history
- Then: The user navigates to the sidebar and clicks the statistics tab
# **Done Done Criteria**
- [x] Push the code to master branch on Git
- [x] Test that the data is accurate (to do so, manually populate Firebase with "questions" data
- [ ] Test that all the correct statistics are being shown
