### ISSUE TITLE
Log out

### ISSUE THREAD

**Issue by makoto0610** [makoto0610/Mobster#12]
# **Task Details**
- [x] Logout screen UI
- [x] User should have access to logout button and taken to log in screen
# **Acceptance Scenarios**
- Given: a user
- When: the user wants to logout of the application
- Then: user clicks the logout button and log out of the application
# **Done Done Criteria**
- [x] Push the code to master on Git
- [x] Test that the logout button lead back to the login screen from all current activities
