### ISSUE TITLE
Open Questions (My Questions)

### ISSUE THREAD

**Issue by makoto0610** [makoto0610/Mobster#18]
# **Tasks**
- [ ] Make UI for open questions (similar to that of closed questions)
- [ ] Retrieve all the open questions from the database for the user
- [ ] When user clicks a question, they will be navigated to the real time result of the question.
# **Acceptance scenarios**
Given: a user
When: User wants to see the past questions
Then: User will navigate to "my questions" and view his/her open questions along with its real time result
# **Done Done Criteria**
- [ ] At least one user test is conducted to see if a user can adequately post a question and view their question.
