### ISSUE TITLE
Closed Questions (My Questions and Home Page)

### ISSUE THREAD

**Issue by makoto0610** [makoto0610/Mobster#19]
# **Tasks**
- [x] Make UI for closed questions
- [x] Retrieve all the closed questions from the database for the user
- [ ] When user clicks a question, they will be navigated to the result of the question.
- [ ] Make connect the closed questions with results for both my questions and home page
# **Acceptance scenarios**
Given: a user
When: User wants to see the past questions
Then: User will navigate to "my questions" and view his/her closed questions
# **Done Done Criteria**
- [ ] At least one user test is conducted see if a user can view their closed questions
