### ISSUE TITLE
As a user, I would like to search questions that I am interested in

### ISSUE THREAD

**Issue by makoto0610** [makoto0610/Mobster#21]
# **Tasks**
- [ ] Implement tags for questions
- [ ] Allow users to search by tags
- [ ] Implement some functionalities such as elastic search
- [ ] Database queries
- [x] UI for search bar

# **Acceptance Scenario**
- Given: a user
- When: a user wants to search questions
- Then: user type keywords in the search bar
# **Done Done Criteria**
- [ ] At least one user test is conducted to see if a user can search for their own question
- [ ] Tags should be functional
