### ISSUE TITLE
Delete flagged questions

### ISSUE THREAD

**Issue by makoto0610** [makoto0610/Mobster#22]
# **Tasks**
- [ ] Query all the flagged questions
- [ ] Create UI to select which ones to delete
- [ ] Remove questions from database
# **Acceptance Scenario**
- Given: a flagged question
- When: an administrator wants to delete flagged questions
- Then: administrator selects questions and delete them
# **Done Done Criteria**
- [ ] An administrator is able to delete a flagged question
