### ISSUE TITLE
Ban users

### ISSUE THREAD

**Issue by makoto0610** [makoto0610/Mobster#23]
# **Tasks**
- [x] Retrieve users and select them to ban
- [x] Once selected the username and password and all questions will be removed from database
# **Acceptance Scenario**
- Given: an administrator and a user
- When: an administrator wants to ban a user
- Then: an administrator would select the user and ban him/her from the application
# **Done Done Criteria**
- [ ] The user should be removed from the database. All the user's info should be deleted as well (statistics, history, username, password, etc.)
