### ISSUE TITLE
View general statistics (Admin)

### ISSUE THREAD

**Issue by makoto0610** [makoto0610/Mobster#24]
# **Tasks**
- [x] Database queries to retrieve number of users and flagged questions
- [x] UI to view those results
# **Acceptance Scenario**
- Given: an administrator
- When: an administrator wants to view and monitor the application
- Then: an administrator logs in, then he/she will be able to see statistics and flagged questions
# **Done Done Criteria**
- [x] The administrator should be able to view the current number of users, current number of ongoing questions, and the current number of flagged questions.
