### ISSUE TITLE
As an administrator, I would like to have a logo for the Application

### ISSUE THREAD

**Issue by makoto0610** [makoto0610/Mobster#26]
# **Tasks**
- [ ] Decide upon a logo
- [ ] Draw the logo out
- [ ] Make the logo to appear on the Android Application
- [ ] incorporate the logo throughout the application
# **Acceptance Scenario**
- [ ] The logo is approved by the client
# **Done Done Criteria**
- [ ] User testing is conducted for feedback about the logo and modified according to feedback
