### ISSUE TITLE
As a user, I would like to comment on the question to state my reasoning.

### ISSUE THREAD

**Issue by makoto0610** [makoto0610/Mobster#27]
# **Tasks**
- [ ] Make user interface to put the comments when voting on a question
- [ ] Store the comments into the database
- [ ] Make all the comments viewable and load more upon the request by user (ie in the results page)
# **Acceptance Scenario**
- Given: a user and comment
- When: user wants to comment on the question
- Then: user types in comment and submit to the question
# **Done Done Criteria**
- [ ] At least one user test is conducted to see if a user can comment and also view comments on a post
