### ISSUE TITLE
As a user, I want to set settings for the Application.

### ISSUE THREAD

**Issue by makoto0610** [makoto0610/Mobster#28]
# **Tasks**
- [x] Make light and dark theme and let user select which
- [x] Make notification available in case user need it
# **Acceptance Scenario**
Given: a user
When: a user wants to make setting for the application
Then: user can make changes as he/she like accordingly 
# **Done Done Criteria**
- [x] User test is conducted to see if adequate settings are provided
- [x] Settings include (at minimum) color preferences, notification preferences
