### ISSUE TITLE
As a user, I want to get reminded of my password

### ISSUE THREAD

**Issue by makoto0610** [makoto0610/Mobster#29]
# **Tasks**
- [ ] Make changes to register screen and let user to put optional email
- [ ] Send email to user in case he/she forgot password
- [ ] Make temporary password and let user to log in
- [ ] Make changes in database accordingly
- [ ] Need to make a new feature so users can add/ change email
# **Acceptance Scenario**
- Given: an email and an user
- When: an user forgets his/her password and want to get reminded
- Then: an user receives a temporary password in email 
# **Done Done Criteria**
- [ ] User test is conducted to see if a user can work through a forgotten password request
- [ ] The user is prompted to reset their password upon entering the temporary password
