### ISSUE TITLE
User testings

### ISSUE THREAD

**Issue by makoto0610** [makoto0610/Mobster#30]
# **Task**
- [x] Conduct user testings
- [x] Fix the issues suggested by users
# **Acceptance Scenario**
- Given: application
- When: when we want to conduct user testings
- Then: user uses the app and gives us final feedbacks.
# **Done Done Criteria**
- [x] Conduct at least one user story for person
- [x] Write down feedbacks
