### ISSUE TITLE
Bug fixes and code review

### ISSUE THREAD

**Issue by makoto0610** [makoto0610/Mobster#31]
# **Tasks**
- [ ] Based on the user testing, fix the bug
- [ ] Conduct code review as a group to improve conciseness and efficiency 
- [ ] Cannot up vote or down vote multiple times
# **Acceptance Scenario**
- Given: code
- When: when we conduct code review as a group
- Then: We look at the code and try to fix bugs and improve
# **Done Done Criteria**
- [ ] Fix all the error found through user tests
- [ ] Fix all the error that we noticed through code review
- [ ] Fix all the error that client specifies
