### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by makoto0610** [makoto0610/Mobster#32]
# **Tasks**
- [ ] Release the application to client and play store
# **Acceptance Scenario**
- Given: client
- When: When we show the application to the client
- Then: Client will hopefully be satisfied
# **Done Done Criteria**
- [ ] Ask the client whether he would like to release the application
- [ ] Ask the client whether he is satisfied with the application
- [ ] Release the application to the Android PlayStore
