### ISSUE TITLE
Loading Statistics

### ISSUE THREAD

**Issue by nathyu** [makoto0610/Mobster#37]
# ****Task Details****
- [ ] Program the backend to query database to retrieve user statistics, including number of questions answered and number of questions asked
# **Acceptance scenarios**
- Given: A registered user
- When: A user wants to check his statistics/history
- Then: The user navigates to the sidebar and clicks the statistics tab
# **Done Done Criteria**
- [x] Push the code to master branch on Git
- [x] Test that all the correct statistics are being shown
