### ISSUE TITLE
Adding Question and Option objects

### ISSUE THREAD

**Issue by cshih299** [makoto0610/Mobster#39]
# ****Task Details****
- [x] Create Question and Option objects
- [x] Populate the database with examples of different asked questions
# **Acceptance scenarios**
- Given: A question
- When: The question needs to be stored
- Then: Multiple functionalities can use this format (such as Create Question, Vote on Question, View Question, and  Statistics) 
# **Done Done Criteria**
- [ ] Push the code to master branch on Git
- [ ] Populated the database with some examples for people to test with
