### ISSUE TITLE
Edge cases handling

### ISSUE THREAD

**Issue by makoto0610** [makoto0610/Mobster#42]
# **Tasks**
- [x] Open questions are sorted in new to old
- [ ] User should only be able to "view" question once in backend
- [ ] User can only up vote or down vote once, without exception to changing mind
- [ ] Time should be updated accordingly, reload option
- [ ] One device at a time
# **Acceptance Scenario** 
# **Done Done Criteria**
- [ ] Consult with client what he desires
- [ ] QA amongst developers and passes the tasks.
