### ISSUE TITLE
Up vote and down vote button

### ISSUE THREAD

**Issue by makoto0610** [makoto0610/Mobster#43]
# **Tasks**
- [x] Implement click-able up vote and down vote button
- [x] Keep track of the user input and make the button light up
- [x] Let user cancel/switch option if they want to
# **Acceptance Scenario**
- Given: user
- When: When user wants to express his/her opinion
- Then: User can vote on the question with up/down vote button
# **Done Done Criteria**
- [x] User can up/down vote question with the record in databse
- [x] Committed and merged with master
