### ISSUE TITLE
Orientation 

### ISSUE THREAD

**Issue by cshih299** [makoto0610/Mobster#47]
# **Tasks**
- [ ] Decide whether the application should accommodate horizontal and vertical orientation
- [ ] Implement the orientation decision
# **Acceptance Scenario**
- Given: User
- When: When user wants to turn his/her phone to use the application
- Then: User's phone should either function when turned horizontally or stay in a vertical orientation
# **Done Done Criteria**
- [ ] User won't break the application when turning his/her phone
- [ ] Committed and merged with master
