### ISSUE TITLE
Flagged Questions

### ISSUE THREAD

**Issue by cshih299** [makoto0610/Mobster#48]
# **Tasks**
- [x] Be able to flag questions from the Vote page so the admin can remove it
# **Acceptance Scenario**
- Given: user
- When: When user does not approve of a question
- Then: User can flag the question
# **Done Done Criteria**
- [x] Completed the UI to add the flag button
- [x] The flag works properly
- [x] Committed and merged with master
