### ISSUE TITLE
Bug Fixes

### ISSUE THREAD

**Issue by cshih299** [makoto0610/Mobster#49]
# **Tasks**
- [x] User should not be able to vote on his/her own question
- [x] User should not be able to vote more than once on a question
- [x] User should not be able to create an account that has already been created (and deleted)
- [x] Identify the Null pointer exception for the Layout-Inflater and what is causing it and fix that error once found

# **Done Done Criteria**
- [x] All of the tasks have been completed
- [x] Committed and merged with master
