### ISSUE TITLE
Persistance in Log in

### ISSUE THREAD

**Issue by makoto0610** [makoto0610/Mobster#5]
# **Task Details**
- [x] Database has to be setup
- [ ] Login can be persisted on the same device
- [ ] Login can be persisted on different devices 
- [ ] Do not have to login again once already logged in
# **Acceptance Scenarios**
- Given: a valid username and password
- When: the user enters the valid username and password
- Then: the user should be taking to the main screen after the login
# **Done Done Criteria**
- [ ] Code is pushed to master on Git
- [ ] Test that whenever a user logs in, when they open the app again, they do not need to login again
- [ ] Test invalid and valid inputs
