### ISSUE TITLE
Figure out why the app occasionally crashes

### ISSUE THREAD

**Issue by cshih299** [makoto0610/Mobster#53]
# **Tasks**
- [ ] Identify the Null pointer exception for the Layout-Inflater and what is causing it
- [ ] Fix that error once found

# **Done Done Criteria**
- [ ] The application does not crash any more from the Layout-Inflater exception
- [ ] Committed and merged with master

**Comment by cshih299** [comment]
Moved to the bugs issue
