### ISSUE TITLE
Admin Delete Users

### ISSUE THREAD

**Issue by esingh7** [makoto0610/Mobster#54]
# **Tasks**
- [x] Deleted user who did not provide an email, does not get deleted properly.
- [x] Solve the issue by creating a new blocked user table in Firebase

# **Done Done Criteria**
- [x] Users without email cannot log in again
