### ISSUE TITLE
Password Security/ Email Verification

### ISSUE THREAD

**Issue by cshih299** [makoto0610/Mobster#55]
# **Tasks**
- [ ] Check that the firebase database is secure
- [ ] Possibly get rid of password info in database
- [ ] Enable email verification

# **Done Done Criteria**
- [ ] Push the code to master
