### ISSUE TITLE
Database setup

### ISSUE THREAD

**Issue by makoto0610** [makoto0610/Mobster#6]
# **Task Details**
- [x] Get a database domain
- [x] Setup so that domain is usable from the Android Application
# **Acceptance Scenarios**
- Given:  An unregistered user
- When: User registers for an account
- Then: Database should insert username/password combination

- Given: A registered user
- When: User attempts to log in
- Then: Database should be able to be queried to check if the user/pass is valid
# **Done Done Criteria**
- [x] Test sample inputs to ensure that things are properly store and retrieved
- [x] Push code to master branch on Git
