### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cshih299** [makoto0610/Mobster#64]
# **Tasks**
- [ ] Write the "Read Me" for general overview of application
- [ ] Write some documentation on how the application runs
- [ ] Do we want to create a tutorial?

# **Done Done Criteria**
- [ ] Push a general draft of these documents onto GitHub
