### ISSUE TITLE
Duration/ Update of Questions

### ISSUE THREAD

**Issue by cshih299** [makoto0610/Mobster#66]
# **Tasks**
- [x] Make sure that the duration of the questions gets updated
- [x] When scroll up, it refreshes the duration and updates questions
- [x] Trending questions and closed question are updated when visiting those tabs (for both home and my questions)

# **Done Done Criteria**
- [x] Push the code to master and functionality works
