### ISSUE TITLE
Login User Interface

### ISSUE THREAD

**Issue by makoto0610** [makoto0610/Mobster#7]
# **Task Details**
- [x] Create UI in Android Studio
- [x] Program backend to authenticate user with database
# **Acceptance Scenarios**
- Given: A log in screen for a user who wants to log in
- When: The user wants to log in to the application
- Then: The user should be notified of a successful login by being directed to the home page. Otherwise, an error message should be displayed.
# **Done Done Criteria**
- [x] Push the code to master on Git
- [x] Test that the login user interface has buttons that can lead to registration and/ or home
